In [6]:
from datasets import load_dataset, concatenate_datasets
import pandas as pd

# MMLU

In [4]:
# https://huggingface.co/datasets/cais/mmlu
all_tasks = ['abstract_algebra', 'anatomy', 'astronomy', 'business_ethics', 'clinical_knowledge', 'college_biology',
             'college_chemistry', 'college_computer_science', 'college_mathematics', 'college_medicine',
             'college_physics', 'computer_security', 'conceptual_physics', 'econometrics', 'electrical_engineering',
             'elementary_mathematics', 'formal_logic', 'global_facts', 'high_school_biology', 'high_school_chemistry',
             'high_school_computer_science', 'high_school_european_history', 'high_school_geography',
             'high_school_government_and_politics', 'high_school_macroeconomics', 'high_school_mathematics',
             'high_school_microeconomics', 'high_school_physics', 'high_school_psychology', 'high_school_statistics',
             'high_school_us_history', 'high_school_world_history', 'human_aging', 'human_sexuality',
             'international_law', 'jurisprudence', 'logical_fallacies', 'machine_learning', 'management', 'marketing',
             'medical_genetics', 'miscellaneous', 'moral_disputes', 'moral_scenarios', 'nutrition', 'philosophy',
             'prehistory', 'professional_accounting', 'professional_law', 'professional_medicine',
             'professional_psychology', 'public_relations', 'security_studies', 'sociology', 'us_foreign_policy',
             'virology', 'world_religions']

subsets = ["college_physics", "conceptual_physics", "high_school_physics"]
datasets = [load_dataset("cais/mmlu", subset, revision="c30699e8356da336a370243923dbaf21066bb9fe") for subset in
            subsets]
mmlu = concatenate_datasets([dataset["test"] for dataset in datasets]).to_pandas()
mmlu

,question,subject,choices,answer
0,The quantum efficiency of a photon detector is...,college_physics,"[an average of 10 times, with an rms deviation...",1
1,White light is normally incident on a puddle o...,college_physics,"[500 nm, 550 nm, 600 nm, 650 nm]",2
2,Which of the following is true about any syste...,college_physics,[There are no changes in the internal energy o...,2
3,The best type of laser with which to do spectr...,college_physics,"[a dye laser, a helium-neon laser, an excimer ...",0
4,Excited states of the helium atom can be chara...,college_physics,"[The Heisenberg uncertainty principle, The Pau...",1
...,...,...,...,...
483,A rock drops onto a pond with a smooth surface...,high_school_physics,"[The wave is moving more slowly., The wave pul...",3
484,Physics students are checking the constant acc...,high_school_physics,"[The ball changes its shape while falling., Th...",3
485,Mercury orbits the sun in about one-fifth of a...,high_school_physics,"[(1/25) AU, (1/9) AU, (1/5) AU, (1/3) AU]",3
486,The Gravitron is a carnival ride that looks li...,high_school_physics,"[μv^2/(rg), r^2v^2/(μg), rg/(μv^2), None of th...",3
487,An artificial satellite orbits Earth just abov...,high_school_physics,"[The satellite now orbits in an ellipse, with ...",1

# SciQ
https://www.kaggle.com/datasets/thedevastator/sciq-a-dataset-for-science-question-answering -> https://huggingface.co/datasets/allenai/sciq

```
DatasetDict({
    train: Dataset({
        features: ['question', 'distractor3', 'distractor1', 'distractor2', 'correct_answer', 'support'],
        num_rows: 11679
    })
    validation: Dataset({
        features: ['question', 'distractor3', 'distractor1', 'distractor2', 'correct_answer', 'support'],
        num_rows: 1000
    })
    test: Dataset({
        features: ['question', 'distractor3', 'distractor1', 'distractor2', 'correct_answer', 'support'],
        num_rows: 1000
    })
})
```

In [5]:
sciq = load_dataset("allenai/sciq", revision="2c94ad3e1aafab77146f384e23536f97a4849815")["train"].to_pandas()
sciq

,question,distractor3,distractor1,distractor2,correct_answer,support
0,What type of organism is commonly used in prep...,viruses,protozoa,gymnosperms,mesophilic organisms,"Mesophiles grow best in moderate temperature, ..."
1,What phenomenon makes global winds blow northe...,tropical effect,muon effect,centrifugal effect,coriolis effect,Without Coriolis Effect the global winds would...
2,Changes from a less-ordered state to a more-or...,endothermic,unbalanced,reactive,exothermic,Summary Changes of state are examples of phase...
3,What is the least dangerous radioactive decay?,zeta decay,beta decay,gamma decay,alpha decay,All radioactive decay is dangerous to living t...
4,Kilauea in hawaii is the world’s most continuo...,magma,greenhouse gases,carbon and smog,smoke and ash,Example 3.5 Calculating Projectile Motion: Hot...
...,...,...,...,...,...,...
11674,The enzyme pepsin plays an important role in t...,lipids,protons,proteins,peptides,Protein A large part of protein digestion take...
11675,What remains a constant of radioactive substan...,acidity,temperature,volatility,rate of decay,The rate of decay of a radioactive substance i...
11676,"Terrestrial ecosystems, also known for their d...",substrates,bisomes,monomes,biomes,"Terrestrial ecosystems, also known for their d..."
11677,High explosives create shock waves that exceed...,turbulence,light speed,ion speed,supersonic,The modern day formulation of gun powder is ca...
11678,What do you call a structure composed of two o...,system,cell,marrow,organ,An organ is a structure composed of two or mor...

# SciBench

https://github.com/mandyyyyii/scibench?tab=readme-ov-file -> https://huggingface.co/datasets/xw27/scibench

In [11]:
scibench = load_dataset("xw27/scibench", revision="93931252bc1b71d495e67390235940643d926958")["train"].to_pandas()
scibench

Repo card metadata block was not found. Setting CardData to empty.

Resolving data files:   0%|          | 0/20 [00:00<?, ?it/s]

,problem_text,answer_latex,answer_number,unit,source,problemid,comment,solution
0,Suppose that $10.0 \mathrm{~mol} \mathrm{C}_2 ...,50.7,50.7,$\mathrm{atm}$,atkins,e1.17(a)(a),,
1,Assume all gases are perfect unless stated oth...,+65.49,+65.49,$\mathrm{kJ} \mathrm{mol}^{-1}$,atkins,e2.21(a),,
2,Assume that all gases are perfect and that dat...,+7.3,+7.3,$\mathrm{kJ} \mathrm{mol}^{-1}$,atkins,e3.19(a),,
3,Assume that all gases are perfect and that dat...,67,67,$\mathrm{J} \mathrm{K}^{-1}$,atkins,e3.1(a)(b),,
4,Assume that all gases are perfect and that dat...,0,0,,atkins,e3.4(a)(a),,
...,...,...,...,...,...,...,...,...
687,One mole of $\mathrm{CO}$ gas is transformed f...,24.4,24.4,$\mathrm{~J} \mathrm{~K}^{-1}$,thermo,5.4,,"\nFor an ideal gas,\r\n$$\r\n\begin{gathered}\..."
688,You are given the following reduction reaction...,-0.041,-0.041,$\mathrm{~V}$,thermo,11.3,,We calculate the desired value of $E^{\circ}$ ...
689,"At $298.15 \mathrm{~K}, \Delta G_f^{\circ}(\ma...",1.51,1.51,$10^4 \mathrm{bar}$,thermo,6.13,,"At equilibrium $\Delta G=G(\mathrm{C}$, graphi..."
690,Imagine tossing a coin 50 times. What are the ...,0.11,0.11,,thermo,12.8,,The trial of interest consists of 50 separate ...
691,In a rotational spectrum of $\operatorname{HBr...,4943,4943,$\mathrm{~K}$,thermo,14.4,,The information provided for this problem dict...

In [12]:
scibench.iloc[0]["problem_text"]

'Suppose that $10.0 \\mathrm{~mol} \\mathrm{C}_2 \\mathrm{H}_6(\\mathrm{~g})$ is confined to $4.860 \\mathrm{dm}^3$ at $27^{\\circ} \\mathrm{C}$. Predict the pressure exerted by the ethane from the perfect gas.'

# ARC AI2 Reasoning Challenge

https://huggingface.co/datasets/allenai/ai2_arc (also https://www.kaggle.com/datasets/jeromeblanchet/arc-ai2-reasoning-challenge?select=ARC-Challenge-Test.csv)

In [2]:
arc_easy = load_dataset("allenai/ai2_arc", "ARC-Easy", revision="210d026faf9955653af8916fad021475a3f00453")[
    "train"].to_pandas()
arc_easy

,id,question,choices,answerKey
0,Mercury_7220990,Which factor will most likely cause a person t...,{'text': ['a leg muscle relaxing after exercis...,B
1,MCAS_2007_8_5189,Lichens are symbiotic organisms made of green ...,"{'text': ['carbon dioxide', 'food', 'protectio...",B
2,Mercury_SC_401169,When a switch is used in an electrical circuit...,"{'text': ['cause the charge to build.', 'incre...",D
3,MCAS_2004_8_27,Which of the following is an example of an ass...,"{'text': ['contact lens', 'motorcycle', 'rainc...",A
4,NYSEDREGENTS_2006_8_10,"Rocks are classified as igneous, metamorphic, ...","{'text': ['their color', 'their shape', 'how t...",3
...,...,...,...,...
2246,CSZ_2009_8_CSZ20770,"Iron oxides, such as rust, form when iron meta...","{'text': ['I and O', 'Ir and O', 'Fe and O', '...",C
2247,Mercury_7181318,When water evaporates from Earth's surface int...,"{'text': ['The mass is reduced.', 'The volume ...",C
2248,Mercury_7010080,Which process directly adds carbon into the at...,"{'text': ['increasing plant populations', 'dec...",C
2249,NCEOGA_2013_8_37,Scientists think that dolphins and whales may ...,"{'text': ['They swim the same way.', 'They eat...",D
2250,Mercury_7188563,A particular organism is able to survive in an...,"{'text': ['swimming in arctic waters', 'eating...",A

In [10]:
arc_easy.iloc[4]["answerKey"]

'3'

In [8]:
# Transformation logic
arc_easy.apply(
    lambda row: pd.Series({
        'question': row['question'],
        'choices': row['choices']['text'],
        'correct_answer': list(row['choices']['label']).index(row['answerKey'])
    }),
    axis=1
)

,question,choices,correct_answer
0,Which factor will most likely cause a person t...,"[a leg muscle relaxing after exercise, a bacte...",1
1,Lichens are symbiotic organisms made of green ...,"[carbon dioxide, food, protection, water]",1
2,When a switch is used in an electrical circuit...,"[cause the charge to build., increase and decr...",3
3,Which of the following is an example of an ass...,"[contact lens, motorcycle, raincoat, coffee pot]",0
4,"Rocks are classified as igneous, metamorphic, ...","[their color, their shape, how they formed, th...",2
...,...,...,...
2246,"Iron oxides, such as rust, form when iron meta...","[I and O, Ir and O, Fe and O, Pb and O]",2
2247,When water evaporates from Earth's surface int...,"[The mass is reduced., The volume is increased...",2
2248,Which process directly adds carbon into the at...,"[increasing plant populations, decreasing anim...",2
2249,Scientists think that dolphins and whales may ...,"[They swim the same way., They eat the same fo...",3
2250,A particular organism is able to survive in an...,"[swimming in arctic waters, eating large amoun...",0

In [8]:
arc_challenge = load_dataset("allenai/ai2_arc", "ARC-Challenge", revision="210d026faf9955653af8916fad021475a3f00453")[
    "train"].to_pandas()
arc_challenge

,id,question,choices,answerKey
0,Mercury_SC_415702,George wants to warm his hands quickly by rubb...,"{'text': ['dry palms', 'wet palms', 'palms cov...",A
1,MCAS_2009_5_6516,Which of the following statements best explain...,"{'text': ['The refrigerator door is smooth.', ...",B
2,Mercury_7233695,A fold observed in layers of sedimentary rock ...,"{'text': ['cooling of flowing magma.', 'conver...",B
3,Mercury_7041615,Which of these do scientists offer as the most...,"{'text': ['worldwide disease', 'global mountai...",D
4,Mercury_7041860,A boat is acted on by a river current flowing ...,"{'text': ['west', 'east', 'north', 'south'], '...",B
...,...,...,...,...
1114,Mercury_SC_415480,Which change would most likely increase the nu...,"{'text': ['flood', 'drought', 'fire', 'landsli...",A
1115,Mercury_7172795,The skin is the largest organ in the human bod...,"{'text': ['It is made of cells.', 'It acts as ...",C
1116,NCEOGA_2013_8_59,Which food provides the most energy for the bo...,"{'text': ['potato', 'meat', 'milk', 'fruit'], ...",D
1117,Mercury_7219643,Screech owls have two color variations-red and...,"{'text': ['nesting', 'feeding', 'reproduction'...",D
1118,Mercury_SC_412487,A scientist is measuring the amount of movemen...,"{'text': ['barometer', 'stopwatch', 'meter sti...",C

# SVAMP
https://huggingface.co/datasets/ChilleD/SVAMP

Vorteil: Distractors!

In [8]:
svamp = load_dataset("ChilleD/SVAMP", revision="5e0bf1e5e7c0e9c4bc39180d224f41f3f801b7ef")["train"].to_pandas()
svamp

,ID,Body,Question,Equation,Answer,Type,question_concat
0,chal-777,There are 87 oranges and 290 bananas in Philip...,How big is each group of bananas?,( 290.0 / 2.0 ),145,Common-Division,There are 87 oranges and 290 bananas in Philip...
1,chal-508,Marco and his dad went strawberry picking. Mar...,How much did Marco's strawberries weigh?,( 30.0 - 11.0 ),19,Subtraction,Marco and his dad went strawberry picking. Mar...
2,chal-896,Edward spent $ 6 to buy 2 books each book cost...,How much did each book cost?,( 6.0 / 2.0 ),3,Common-Division,Edward spent $ 6 to buy 2 books each book cost...
3,chal-923,Frank was reading through his favorite book. T...,How many pages are in each chapter?,( 594.0 / 3.0 ),198,Common-Division,Frank was reading through his favorite book. T...
4,chal-34,There were 78 dollars in Olivia's wallet. She ...,How much money does she have left?,( 78.0 - 15.0 ),63,Subtraction,There were 78 dollars in Olivia's wallet. She ...
...,...,...,...,...,...,...,...
695,chal-690,Randy has 58 blocks. He uses 27 blocks to buil...,How many blocks did he use to build the tower ...,( 27.0 + 53.0 ),80,Addition,Randy has 58 blocks. He uses 27 blocks to buil...
696,chal-56,A farmer had 90 tomatoes in his garden. If he ...,How many tomatoes did he pick in all?,( 154.0 + 50.0 ),204,Addition,A farmer had 90 tomatoes in his garden. If he ...
697,chal-479,He then went to see the oranges being harveste...,How many sacks of unripe oranges will they hav...,( 24.0 * 45.0 ),1080,Multiplication,He then went to see the oranges being harveste...
698,chal-421,Julia played tag with 11 kids on monday. She p...,How many more kids did she play with on tuesda...,( 12.0 - 11.0 ),1,Subtraction,Julia played tag with 11 kids on monday. She p...
699,chal-756,Bryan took a look at his books as well. If he ...,How many bookshelves does he have?,( 42.0 / 2.0 ),21,Common-Division,Bryan took a look at his books as well. If he ...

In [9]:
svamp.iloc[0]

ID                                                          chal-777
Body               There are 87 oranges and 290 bananas in Philip...
Question                           How big is each group of bananas?
Equation                                             ( 290.0 / 2.0 )
Answer                                                           145
Type                                                 Common-Division
question_concat    There are 87 oranges and 290 bananas in Philip...
Name: 0, dtype: object

# GSM8K

https://huggingface.co/datasets/openai/gsm8k

Alternative: GSM-MC

In [18]:
gsm8k = load_dataset("openai/gsm8k", "main", revision="e53f048856ff4f594e959d75785d2c2d37b678ee")["train"].to_pandas()
gsm8k

,question,answer
0,Natalia sold clips to 48 of her friends in Apr...,Natalia sold 48/2 = <<48/2=24>>24 clips in May...
1,Weng earns $12 an hour for babysitting. Yester...,Weng earns 12/60 = $<<12/60=0.2>>0.2 per minut...
2,Betty is saving money for a new wallet which c...,"In the beginning, Betty has only 100 / 2 = $<<..."
3,"Julie is reading a 120-page book. Yesterday, s...",Maila read 12 x 2 = <<12*2=24>>24 pages today....
4,James writes a 3-page letter to 2 different fr...,He writes each friend 3*2=<<3*2=6>>6 pages a w...
...,...,...
7468,"Very early this morning, Elise left home in a ...","For the distance she traveled, Elise paid 23 -..."
7469,Josh is saving up for a box of cookies. To rai...,He makes $.5 profit on each bracelet because 1...
7470,Colin can skip at six times the speed that Bra...,Tony can skip at twice the speed that Bruce ca...
7471,"Janet, a third grade teacher, is picking up th...",Janet needs 35 lunches for the kids + 5 for th...
7472,"At 30, Anika is 4/3 the age of Maddie. What wo...","If Anika is 30 now, in 15 years, she'll be 30+..."

In [26]:
gsm8k.iloc[345]["answer"]

"The amount of money deducted from Adam's daily pay is $40 / 10 = $<<40/10=4>>4.\nSo after deducting 10%, Adam’s daily pay is $40 – $4 = $<<40-4=36>>36.\nThis means that in 30 days he earns $36 * 30 = $<<36*30=1080>>1080.\n#### 1,080"

In [25]:
indices = gsm8k[gsm8k['answer'].str.contains("1,080", na=False)].index
indices

Index([345], dtype='int64')

In [13]:
arc_challenge.ilo

,id,question,choices,answerKey
0,Mercury_SC_415702,George wants to warm his hands quickly by rubb...,"{'text': ['dry palms', 'wet palms', 'palms cov...",A
1,MCAS_2009_5_6516,Which of the following statements best explain...,"{'text': ['The refrigerator door is smooth.', ...",B
2,Mercury_7233695,A fold observed in layers of sedimentary rock ...,"{'text': ['cooling of flowing magma.', 'conver...",B
3,Mercury_7041615,Which of these do scientists offer as the most...,"{'text': ['worldwide disease', 'global mountai...",D
4,Mercury_7041860,A boat is acted on by a river current flowing ...,"{'text': ['west', 'east', 'north', 'south'], '...",B
...,...,...,...,...
1114,Mercury_SC_415480,Which change would most likely increase the nu...,"{'text': ['flood', 'drought', 'fire', 'landsli...",A
1115,Mercury_7172795,The skin is the largest organ in the human bod...,"{'text': ['It is made of cells.', 'It acts as ...",C
1116,NCEOGA_2013_8_59,Which food provides the most energy for the bo...,"{'text': ['potato', 'meat', 'milk', 'fruit'], ...",D
1117,Mercury_7219643,Screech owls have two color variations-red and...,"{'text': ['nesting', 'feeding', 'reproduction'...",D
1118,Mercury_SC_412487,A scientist is measuring the amount of movemen...,"{'text': ['barometer', 'stopwatch', 'meter sti...",C